name: llm_tools_suite
description: A Flutter app for AI-powered productivity tools
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Dependencies
  cupertino_icons: ^1.0.6

  # HTTP Requests
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2

  # File Operations
  file_picker: ^6.1.1

  # CSV Processing
  csv: ^5.0.2

  # URL Launcher
  url_launcher: ^6.2.1

  # Markdown Support
  flutter_markdown: ^0.6.18

  # Icons
  flutter_svg: ^2.0.9

  # PDF Processing
  syncfusion_flutter_pdf: ^24.2.9

  # Word Document Processing
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
